version: '3'
services:

  elastic:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: jsonql-hibernate-search-elastic
    container_name: jsonql-hibernate-search-elastic
    hostname: jsonql-hibernate-search-elastic
    environment:
      discovery.type: single-node # forces development mode, see https://www.elastic.co/guide/en/elasticsearch/reference/6.4/docker.html#docker-cli-run
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"
